services:
  api-a:
    extends:
      file: compose.base.yml
      service: api-a
    environment:
      API_PORT: "8000"
      SERVICE_MODE: infra-dev
      MODEL_REQUIRED: "false"
      AUTH_ENABLED: "false"
    volumes:
      - ../src:/app/src:ro
      - ../configs:/app/configs:ro
  api-b:
    extends:
      file: compose.base.yml
      service: api-b
    environment:
      API_PORT: "8000"
      SERVICE_MODE: infra-dev
      MODEL_REQUIRED: "false"
      AUTH_ENABLED: "false"
    volumes:
      - ../src:/app/src:ro
      - ../configs:/app/configs:ro
  nginx:
    extends:
      file: compose.base.yml
      service: nginx

networks:
  edge_net:
    driver: bridge
  control_net:
    driver: bridge
    internal: true
  egress_net:
    driver: bridge
