#!/usr/bin/env python3
"""测试环境一键引导：SSH 安装 Docker/Git/uv，打包上传项目，写入 .env，尝试构建并启动。

环境变量（必填）:
  GYCLOUD_SSH_PASS   SSH root 密码
  TT_PG_PASS         PostgreSQL 密码（用户 postgres）

可选:
  TT_LOCAL_ROOT      本地项目根目录（默认为本仓库根目录）
  TT_GIT_REPO_URL    若设置则优先 git clone，不上传本地包
  OPENAI_API_KEY     写入远程 .env（不设则远程为占位符，需手动改）
  TT_PG_USER         默认 postgres
  TT_PG_HOST         默认 tt-postgres
  TT_PG_PORT         默认 5432
  TT_PG_DB           默认 tt

不在仓库中保存任何密码。
"""

from __future__ import annotations

import argparse
import io
import os
import sys
import tarfile
import tempfile
from pathlib import Path
from urllib.parse import quote_plus

import paramiko

ROOT = Path(__file__).resolve().parents[1]

SKIP_SUBSTR = (
    "__pycache__",
    ".venv",
    "/.git/",
    "\\.git\\",
    ".vector_store",
    "dev_databases.zip",
    "/dev.zip",
    "\\dev.zip",
    ".pytest_cache",
    ".mypy_cache",
)


def should_skip(path: Path, root: Path) -> bool:
    try:
        rel = path.relative_to(root).as_posix()
    except ValueError:
        return True
    if path.is_dir() and rel in (".git", ".venv", ".vector_store", "__pycache__"):
        return True
    lower = rel.lower()
    return any(s in lower for s in SKIP_SUBSTR)


def make_source_tar(project_root: Path) -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz", format=tarfile.GNU_FORMAT) as tar:
        for p in sorted(project_root.rglob("*")):
            if p.is_dir():
                continue
            if should_skip(p, project_root):
                continue
            arc = Path("tt-ai-main") / p.relative_to(project_root)
            tar.add(p, arcname=arc.as_posix(), recursive=False)
    return buf.getvalue()


def build_env_file() -> bytes:
    pg_user = os.environ.get("TT_PG_USER", "postgres")
    pg_pass = os.environ["TT_PG_PASS"]
    pg_host = os.environ.get("TT_PG_HOST", "tt-postgres")
    pg_port = os.environ.get("TT_PG_PORT", "5432")
    pg_db = os.environ.get("TT_PG_DB", "tt")
    u = quote_plus(pg_user)
    p = quote_plus(pg_pass)
    db_url = f"postgresql+asyncpg://{u}:{p}@{pg_host}:{pg_port}/{pg_db}"
    okey = os.environ.get("OPENAI_API_KEY", "changeme-set-OPENAI_API_KEY")
    lines = [
        "# Generated by bootstrap_test_server.py — 请勿提交到 Git",
        "ENV=test",
        "",
        f"DATABASE_URL={db_url}",
        f"DATABASE_URL_ADMIN={db_url}",
        "",
        "# LLM（测试环境请设置真实 Key）",
        f"OPENAI_API_KEY={okey}",
        "OPENAI_BASE_URL=https://integrate.api.nvidia.com/v1",
        "MODEL_NAME=qwen/qwen3-next-80b-a3b-instruct",
        "",
        "# 测试环境关闭鉴权，避免必须配置 tt-api",
        "AUTH_ENABLED=false",
        "",
        "NL2SQL_DB_SCHEMA=ai_views",
        "RAG_QA_FILE_PATH=configs/semantic/qa.md",
        "RAG_SEMANTIC_FILE_PATH=configs/semantic/semantic.md",
        "RAG_FAISS_INDEX_PATH=.vector_store/nl2sql_qa",
        "RAG_SEMANTIC_FAISS_INDEX_PATH=.vector_store/nl2sql_semantic",
        "",
        "EMBEDDING_API_KEY=not-needed",
        "EMBEDDING_BASE_URL=http://127.0.0.1:1234/v1",
        "EMBEDDING_MODEL=text-embedding-mxbai-embed-large-v1",
        "",
        "# 无 embedding 服务：跳过启动时 RAG 索引同步（评测/联调可开；完整 RAG 评测前改 false）",
        "SKIP_RAG_STARTUP_SYNC=true",
        "RAG_STARTUP_SYNC_STRICT=false",
        "API_PORT=8000",
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def ssh_connect(host: str, port: int, password: str) -> paramiko.SSHClient:
    c = paramiko.SSHClient()
    c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    c.connect(
        host,
        port=port,
        username="root",
        password=password,
        timeout=60,
        banner_timeout=60,
        auth_timeout=60,
    )
    return c


def run_remote(client: paramiko.SSHClient, cmd: str, timeout: int = 600) -> tuple[int, str]:
    _stdin, stdout, stderr = client.exec_command(cmd, timeout=timeout)
    out = stdout.read().decode("utf-8", "replace")
    err = stderr.read().decode("utf-8", "replace")
    code = stdout.channel.recv_exit_status()
    return code, out + err


def run_remote_script(client: paramiko.SSHClient, body: str, timeout: int = 600) -> tuple[int, str]:
    sftp = client.open_sftp()
    remote = "/tmp/tt_ai_bootstrap.sh"
    script = "#!/bin/bash\nset -e\n" + body
    with sftp.file(remote, "wb") as f:
        f.write(script.encode("utf-8"))
    sftp.close()
    return run_remote(client, f"chmod +x {remote} && bash {remote}", timeout=timeout)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="tunnel.gycloud.net")
    parser.add_argument("--port", type=int, default=60022)
    parser.add_argument(
        "--local-root",
        default=str(ROOT),
        help="本地项目根（未设置 TT_GIT_REPO_URL 时使用）",
    )
    args = parser.parse_args()

    ssh_pass = os.environ.get("GYCLOUD_SSH_PASS")
    if not ssh_pass or "TT_PG_PASS" not in os.environ:
        print("请设置 GYCLOUD_SSH_PASS 与 TT_PG_PASS", file=sys.stderr)
        sys.exit(1)

    git_url = os.environ.get("TT_GIT_REPO_URL", "").strip()
    local_root = Path(args.local_root).resolve()

    print(">>> 连接 SSH …")
    client = ssh_connect(args.host, args.port, ssh_pass)

    setup_script = r"""
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y ca-certificates curl git gnupg lsb-release tar

if ! command -v docker >/dev/null 2>&1; then
  echo ">>> 安装 Docker …"
  curl -fsSL https://get.docker.com -o /tmp/get-docker.sh || true
  if [ -f /tmp/get-docker.sh ]; then
    sh /tmp/get-docker.sh || echo "Docker 安装脚本失败（可能在无特权容器内）"
  fi
fi
if command -v docker >/dev/null 2>&1; then
  docker --version || true
  (systemctl enable docker 2>/dev/null && systemctl start docker) || true
  service docker start 2>/dev/null || true
fi

if ! command -v uv >/dev/null 2>&1; then
  echo ">>> 安装 uv …"
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="/root/.local/bin:$PATH"
command -v uv && uv --version || true
echo ">>> 基础环境就绪"
"""
    code, out = run_remote_script(client, setup_script, timeout=900)
    print(out)
    if code != 0:
        print(f"警告: 远程基础脚本 exit={code}", file=sys.stderr)

    if git_url:
        print(f">>> git clone {git_url} …")
        clone_cmd = f"rm -rf /opt/tt-ai-main && mkdir -p /opt && git clone --depth 1 {git_url} /opt/tt-ai-main"
        code, out = run_remote(client, clone_cmd, timeout=600)
        print(out)
        if code != 0:
            print("git clone 失败，退出", file=sys.stderr)
            sys.exit(code)
    else:
        print(">>> 打包本地上传 …")
        blob = make_source_tar(local_root)
        print(f"    tar 大小: {len(blob) / 1024 / 1024:.2f} MB")
        sftp = client.open_sftp()
        with sftp.file("/tmp/tt-ai-src.tgz", "wb") as rf:
            rf.write(blob)
        sftp.close()
        extract = """
rm -rf /opt/tt-ai-main
tar xzf /tmp/tt-ai-src.tgz -C /opt
ls -la /opt/tt-ai-main | head
"""
        code, out = run_remote_script(client, extract, timeout=300)
        print(out)
        if code != 0:
            sys.exit(code)

    print(">>> 写入 /opt/tt-ai-main/.env …")
    env_bytes = build_env_file()
    sftp = client.open_sftp()
    with sftp.file("/opt/tt-ai-main/.env", "wb") as wf:
        wf.write(env_bytes)
    sftp.close()

    print(">>> uv sync（宿主机运行，不依赖 Docker 守护进程）…")
    sync = r"""
export PATH="/root/.local/bin:$PATH"
cd /opt/tt-ai-main
uv sync
uv run python -c "import sys; print('python', sys.version)"
"""
    code, out = run_remote_script(client, sync, timeout=1200)
    print(out)
    if code != 0:
        print(f"uv sync 失败 exit={code}", file=sys.stderr)

    print(">>> 尝试 Docker Compose 构建 …")
    compose = r"""
export PATH="/root/.local/bin:$PATH"
cd /opt/tt-ai-main
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  docker compose -f docker/docker-compose.yml build
  docker compose -f docker/docker-compose.yml up -d
  docker compose -f docker/docker-compose.yml ps
else
  echo "Docker 不可用，跳过 compose；已可用 uv run 手动启动："
  echo "  cd /opt/tt-ai-main && uv run python main.py prod"
fi
"""
    code, out = run_remote_script(client, compose, timeout=1800)
    print(out)

    print(">>> 尝试后台启动（uv，若 compose 未起服务）…")
    start_uv = r"""
export PATH="/root/.local/bin:$PATH"
cd /opt/tt-ai-main
if ! curl -sf http://127.0.0.1:8000/docs >/dev/null 2>&1; then
  nohup uv run python main.py prod >> /tmp/tt-ai.log 2>&1 &
  sleep 5
  tail -40 /tmp/tt-ai.log || true
fi
curl -sf -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/docs || echo " docs_unreachable"
"""
    code, out = run_remote_script(client, start_uv, timeout=120)
    print(out)

    client.close()
    print(">>> 完成。请检查：1) OPENAI_API_KEY  2) 嵌入服务或 RAG 配置  3) /tmp/tt-ai.log")


if __name__ == "__main__":
    main()
